# Generated by Django 2.2.7 on 2019-11-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speagle', '0002_emailkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailkey',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='validated'),
        ),
    ]
