# Generated by Django 3.0 on 2019-12-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hash_id',
            field=models.CharField(default='35cf04337c6f38dbbd42f94d07da9369', max_length=50, unique=True, verbose_name='hashed id'),
        ),
    ]
